-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 20:36:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `status` TINYINT NOT NULL,
  `lastLogin` DATETIME NOT NULL,
  `permissionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_permission_idx` (`permissionId` ASC) VISIBLE,
  CONSTRAINT `fk_permission`
    FOREIGN KEY (`permissionId`)
    REFERENCES `hotel`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `hotel`.`accommodation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`accommodation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`banner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NOT NULL,
  `slogan` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `detail` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`coupon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `date` DATE NULL,
  `expired` TINYINT NULL,
  `discount` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checkin` DATE NOT NULL,
  `checkout` DATE NOT NULL,
  `qty` INT UNSIGNED NOT NULL,
  `dateConfirm` DATETIME NOT NULL,
  `createAt` DATETIME NOT NULL,
  `subTotal` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `accommodationId` INT NOT NULL,
  `userId` INT NOT NULL,
  `couponId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accomodations_10_idx` (`accommodationId` ASC) VISIBLE,
  INDEX `fk_user_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_coupon_idx` (`couponId` ASC) VISIBLE,
  CONSTRAINT `fk_accomodations_10`
    FOREIGN KEY (`accommodationId`)
    REFERENCES `hotel`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`userId`)
    REFERENCES `hotel`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coupon`
    FOREIGN KEY (`couponId`)
    REFERENCES `hotel`.`coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `hotel`.`reservationServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservationServices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reservationId` INT NOT NULL,
  `serviceId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservationServices_1_idx` (`reservationId` ASC) VISIBLE,
  INDEX `fk_reservationServices_2_idx` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `fk_reservationServices_1`
    FOREIGN KEY (`reservationId`)
    REFERENCES `hotel`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservationServices_2`
    FOREIGN KEY (`serviceId`)
    REFERENCES `hotel`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `hotel`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `streetName` VARCHAR(20) NOT NULL,
  `streetNumber` INT UNSIGNED NULL,
  `neighborhood` VARCHAR(50) NOT NULL,
  `city` VARCHAR(80) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `postalCode` VARCHAR(8) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`userId`)
    REFERENCES `hotel`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `hotel`.`contact ***`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`contact ***` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `phone` VARCHAR(9) NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`product ***`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`product ***` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`consumption ***`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`consumption ***` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reservationId` INT NOT NULL,
  `productId` INT NOT NULL,
  `qty` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_idx` (`reservationId` ASC) VISIBLE,
  INDEX `fk_product_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_reservation`
    FOREIGN KEY (`reservationId`)
    REFERENCES `hotel`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product`
    FOREIGN KEY (`productId`)
    REFERENCES `hotel`.`product ***` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `hotel`.`review ***`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`review ***` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `rating` TINYINT NOT NULL,
  `reservationId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_idx` (`reservationId` ASC) VISIBLE,
  CONSTRAINT `fk_reservation`
    FOREIGN KEY (`reservationId`)
    REFERENCES `hotel`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;