-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 16:27:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `hotel`.`accomodations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`accomodations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NOT NULL,
  `accomodation` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `userId` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`banner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NOT NULL,
  `slogan` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `detail` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `checkin` DATE NOT NULL,
  `checkout` DATE NOT NULL,
  `qty` INT UNSIGNED NOT NULL,
  `accommodationId` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `hotel`.`reservationServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservationServices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reservationId` INT NOT NULL,
  `serviceId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservationServices_1_idx` (`reservationId` ASC) VISIBLE,
  INDEX `fk_reservationServices_2_idx` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `fk_reservationServices_1`
    FOREIGN KEY (`reservationId`)
    REFERENCES `hotel`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservationServices_2`
    FOREIGN KEY (`serviceId`)
    REFERENCES `hotel`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `hotel`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`type` ASC) VISIBLE,
  INDEX `fk_user_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`userid`)
    REFERENCES `hotel`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
